version: "3.9"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - order
      - product

  auth:
    build: ./auth
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq

  order:
    build: ./order
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - rabbitmq

  product:
    build: ./product
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web U